# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bhello.proto\x12\x05hello\"\x1f\n\x0cPrintRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x0c\n\nPrintReply2:\n\x05Hello\x12\x31\n\x05write\x12\x13.hello.PrintRequest\x1a\x11.hello.PrintReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PRINTREQUEST']._serialized_start=22
  _globals['_PRINTREQUEST']._serialized_end=53
  _globals['_PRINTREPLY']._serialized_start=55
  _globals['_PRINTREPLY']._serialized_end=67
  _globals['_HELLO']._serialized_start=69
  _globals['_HELLO']._serialized_end=127
# @@protoc_insertion_point(module_scope)
