# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csensor.proto\"\x9e\x01\n\x07Reading\x12\n\n\x02Id\x18\x01 \x01(\x05\x12!\n\x04type\x18\x02 \x01(\x0e\x32\x13.Reading.SensorType\x12\r\n\x05value\x18\x03 \x01(\x02\x12\x0c\n\x04unit\x18\x04 \x01(\t\"G\n\nSensorType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08HUMIDITY\x10\x01\x12\x0c\n\x08PRESSURE\x10\x02\x12\x10\n\x0c\x41\x43\x43\x45LERATION\x10\x03\x62\x06proto3'
)



_READING_SENSORTYPE = _descriptor.EnumDescriptor(
  name='SensorType',
  full_name='Reading.SensorType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='HUMIDITY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRESSURE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACCELERATION', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=104,
  serialized_end=175,
)
_sym_db.RegisterEnumDescriptor(_READING_SENSORTYPE)


_READING = _descriptor.Descriptor(
  name='Reading',
  full_name='Reading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='Reading.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='Reading.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Reading.value', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='unit', full_name='Reading.unit', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _READING_SENSORTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=175,
)

_READING.fields_by_name['type'].enum_type = _READING_SENSORTYPE
_READING_SENSORTYPE.containing_type = _READING
DESCRIPTOR.message_types_by_name['Reading'] = _READING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reading = _reflection.GeneratedProtocolMessageType('Reading', (_message.Message,), {
  'DESCRIPTOR' : _READING,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:Reading)
  })
_sym_db.RegisterMessage(Reading)


# @@protoc_insertion_point(module_scope)
