# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: factorial_checker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x66\x61\x63torial_checker.proto\x12\x11\x66\x61\x63torial_checker\"\x1e\n\rNumberRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\" \n\x0eNumberResponse\x12\x0e\n\x06number\x18\x01 \x01(\x05\"0\n\x0c\x43heckRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\tfactorial\x18\x02 \x01(\x03\"\x1f\n\rCheckResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xc7\x01\n\x10\x46\x61\x63torialChecker\x12\\\n\x13RequestRandomNumber\x12 .factorial_checker.NumberRequest\x1a!.factorial_checker.NumberResponse\"\x00\x12U\n\x0e\x43heckFactorial\x12\x1f.factorial_checker.CheckRequest\x1a .factorial_checker.CheckResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'factorial_checker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NUMBERREQUEST']._serialized_start=46
  _globals['_NUMBERREQUEST']._serialized_end=76
  _globals['_NUMBERRESPONSE']._serialized_start=78
  _globals['_NUMBERRESPONSE']._serialized_end=110
  _globals['_CHECKREQUEST']._serialized_start=112
  _globals['_CHECKREQUEST']._serialized_end=160
  _globals['_CHECKRESPONSE']._serialized_start=162
  _globals['_CHECKRESPONSE']._serialized_end=193
  _globals['_FACTORIALCHECKER']._serialized_start=196
  _globals['_FACTORIALCHECKER']._serialized_end=395
# @@protoc_insertion_point(module_scope)
