# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import factorial_checker_pb2 as factorial__checker__pb2


class FactorialCheckerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestRandomNumber = channel.unary_unary(
                '/factorial_checker.FactorialChecker/RequestRandomNumber',
                request_serializer=factorial__checker__pb2.NumberRequest.SerializeToString,
                response_deserializer=factorial__checker__pb2.NumberResponse.FromString,
                )
        self.CheckFactorial = channel.unary_unary(
                '/factorial_checker.FactorialChecker/CheckFactorial',
                request_serializer=factorial__checker__pb2.CheckRequest.SerializeToString,
                response_deserializer=factorial__checker__pb2.CheckResponse.FromString,
                )


class FactorialCheckerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestRandomNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckFactorial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FactorialCheckerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestRandomNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestRandomNumber,
                    request_deserializer=factorial__checker__pb2.NumberRequest.FromString,
                    response_serializer=factorial__checker__pb2.NumberResponse.SerializeToString,
            ),
            'CheckFactorial': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckFactorial,
                    request_deserializer=factorial__checker__pb2.CheckRequest.FromString,
                    response_serializer=factorial__checker__pb2.CheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'factorial_checker.FactorialChecker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FactorialChecker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestRandomNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/factorial_checker.FactorialChecker/RequestRandomNumber',
            factorial__checker__pb2.NumberRequest.SerializeToString,
            factorial__checker__pb2.NumberResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckFactorial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/factorial_checker.FactorialChecker/CheckFactorial',
            factorial__checker__pb2.CheckRequest.SerializeToString,
            factorial__checker__pb2.CheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
