# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: door.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='door.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndoor.proto\"\xcf\x01\n\x0e\x43ontrolMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12(\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\x17.ControlMessage.Command\x12\"\n\x04mode\x18\x03 \x01(\x0e\x32\x14.ControlMessage.Mode\x12\x0c\n\x04time\x18\x04 \x01(\x05\"0\n\x07\x43ommand\x12\x10\n\x0c\x43HECK_STATUS\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\"#\n\x04Mode\x12\x0b\n\x07VEHICLE\x10\x00\x12\x0e\n\nPEDESTRIAN\x10\x01\"\xa3\x01\n\x0fResponseMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\'\n\x06result\x18\x02 \x01(\x0e\x32\x17.ResponseMessage.Result\"[\n\x06Result\x12\x06\n\x02OK\x10\x00\x12\x10\n\x0c\x41LREADY_OPEN\x10\x01\x12\x12\n\x0e\x41LREADY_CLOSED\x10\x02\x12\x12\n\x0eOBSTACLE_FOUND\x10\x03\x12\x0f\n\x0bMOTOR_ERROR\x10\x04\x62\x06proto3'
)



_CONTROLMESSAGE_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='ControlMessage.Command',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CHECK_STATUS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=137,
  serialized_end=185,
)
_sym_db.RegisterEnumDescriptor(_CONTROLMESSAGE_COMMAND)

_CONTROLMESSAGE_MODE = _descriptor.EnumDescriptor(
  name='Mode',
  full_name='ControlMessage.Mode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VEHICLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PEDESTRIAN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=187,
  serialized_end=222,
)
_sym_db.RegisterEnumDescriptor(_CONTROLMESSAGE_MODE)

_RESPONSEMESSAGE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='ResponseMessage.Result',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_OPEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_CLOSED', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OBSTACLE_FOUND', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTOR_ERROR', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=297,
  serialized_end=388,
)
_sym_db.RegisterEnumDescriptor(_RESPONSEMESSAGE_RESULT)


_CONTROLMESSAGE = _descriptor.Descriptor(
  name='ControlMessage',
  full_name='ControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ControlMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='ControlMessage.command', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='ControlMessage.mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='ControlMessage.time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CONTROLMESSAGE_COMMAND,
    _CONTROLMESSAGE_MODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=222,
)


_RESPONSEMESSAGE = _descriptor.Descriptor(
  name='ResponseMessage',
  full_name='ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ResponseMessage.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='ResponseMessage.result', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSEMESSAGE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=388,
)

_CONTROLMESSAGE.fields_by_name['command'].enum_type = _CONTROLMESSAGE_COMMAND
_CONTROLMESSAGE.fields_by_name['mode'].enum_type = _CONTROLMESSAGE_MODE
_CONTROLMESSAGE_COMMAND.containing_type = _CONTROLMESSAGE
_CONTROLMESSAGE_MODE.containing_type = _CONTROLMESSAGE
_RESPONSEMESSAGE.fields_by_name['result'].enum_type = _RESPONSEMESSAGE_RESULT
_RESPONSEMESSAGE_RESULT.containing_type = _RESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['ControlMessage'] = _CONTROLMESSAGE
DESCRIPTOR.message_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlMessage = _reflection.GeneratedProtocolMessageType('ControlMessage', (_message.Message,), {
  'DESCRIPTOR' : _CONTROLMESSAGE,
  '__module__' : 'door_pb2'
  # @@protoc_insertion_point(class_scope:ControlMessage)
  })
_sym_db.RegisterMessage(ControlMessage)

ResponseMessage = _reflection.GeneratedProtocolMessageType('ResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEMESSAGE,
  '__module__' : 'door_pb2'
  # @@protoc_insertion_point(class_scope:ResponseMessage)
  })
_sym_db.RegisterMessage(ResponseMessage)


# @@protoc_insertion_point(module_scope)
