# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: door.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='door.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ndoor.proto\"\xcd\x01\n\rRemoteControl\x12\n\n\x02id\x18\x01 \x01(\x05\x12$\n\x04\x63mnd\x18\x02 \x01(\x0e\x32\x16.RemoteControl.Command\x12%\n\x04mode\x18\x03 \x01(\x0e\x32\x17.RemoteControl.OpenMode\x12\x0c\n\x04time\x18\x04 \x01(\x05\"0\n\x07\x43ommand\x12\x08\n\x04OPEN\x10\x00\x12\t\n\x05\x43LOSE\x10\x01\x12\x10\n\x0c\x43HECK_STATUS\x10\x02\"#\n\x08OpenMode\x12\x0b\n\x07VEHICLE\x10\x00\x12\n\n\x06WALKER\x10\x01\"\xe5\x01\n\nDoorSensor\x12\n\n\x02id\x18\x01 \x01(\x05\x12&\n\x08response\x18\x02 \x01(\x0e\x32\x14.DoorSensor.Response\x12 \n\x05state\x18\x03 \x01(\x0e\x32\x11.DoorSensor.State\"0\n\x08Response\x12\x07\n\x03\x41\x43K\x10\x00\x12\x10\n\x0c\x43HECK_STATUS\x10\x01\x12\t\n\x05\x45RROR\x10\x02\"O\n\x05State\x12\x10\n\x0c\x41LREADY_OPEN\x10\x00\x12\x11\n\rALREADY_CLOSE\x10\x01\x12\x10\n\x0cOBSTACLE_ERR\x10\x02\x12\x0f\n\x0bMOTOR_ERROR\x10\x03\x62\x06proto3'
)



_REMOTECONTROL_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='RemoteControl.Command',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHECK_STATUS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=135,
  serialized_end=183,
)
_sym_db.RegisterEnumDescriptor(_REMOTECONTROL_COMMAND)

_REMOTECONTROL_OPENMODE = _descriptor.EnumDescriptor(
  name='OpenMode',
  full_name='RemoteControl.OpenMode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VEHICLE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WALKER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=185,
  serialized_end=220,
)
_sym_db.RegisterEnumDescriptor(_REMOTECONTROL_OPENMODE)

_DOORSENSOR_RESPONSE = _descriptor.EnumDescriptor(
  name='Response',
  full_name='DoorSensor.Response',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CHECK_STATUS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=323,
  serialized_end=371,
)
_sym_db.RegisterEnumDescriptor(_DOORSENSOR_RESPONSE)

_DOORSENSOR_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='DoorSensor.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALREADY_OPEN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_CLOSE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OBSTACLE_ERR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MOTOR_ERROR', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=373,
  serialized_end=452,
)
_sym_db.RegisterEnumDescriptor(_DOORSENSOR_STATE)


_REMOTECONTROL = _descriptor.Descriptor(
  name='RemoteControl',
  full_name='RemoteControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='RemoteControl.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmnd', full_name='RemoteControl.cmnd', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='RemoteControl.mode', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='RemoteControl.time', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _REMOTECONTROL_COMMAND,
    _REMOTECONTROL_OPENMODE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=220,
)


_DOORSENSOR = _descriptor.Descriptor(
  name='DoorSensor',
  full_name='DoorSensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DoorSensor.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='DoorSensor.response', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='state', full_name='DoorSensor.state', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _DOORSENSOR_RESPONSE,
    _DOORSENSOR_STATE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=452,
)

_REMOTECONTROL.fields_by_name['cmnd'].enum_type = _REMOTECONTROL_COMMAND
_REMOTECONTROL.fields_by_name['mode'].enum_type = _REMOTECONTROL_OPENMODE
_REMOTECONTROL_COMMAND.containing_type = _REMOTECONTROL
_REMOTECONTROL_OPENMODE.containing_type = _REMOTECONTROL
_DOORSENSOR.fields_by_name['response'].enum_type = _DOORSENSOR_RESPONSE
_DOORSENSOR.fields_by_name['state'].enum_type = _DOORSENSOR_STATE
_DOORSENSOR_RESPONSE.containing_type = _DOORSENSOR
_DOORSENSOR_STATE.containing_type = _DOORSENSOR
DESCRIPTOR.message_types_by_name['RemoteControl'] = _REMOTECONTROL
DESCRIPTOR.message_types_by_name['DoorSensor'] = _DOORSENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RemoteControl = _reflection.GeneratedProtocolMessageType('RemoteControl', (_message.Message,), {
  'DESCRIPTOR' : _REMOTECONTROL,
  '__module__' : 'door_pb2'
  # @@protoc_insertion_point(class_scope:RemoteControl)
  })
_sym_db.RegisterMessage(RemoteControl)

DoorSensor = _reflection.GeneratedProtocolMessageType('DoorSensor', (_message.Message,), {
  'DESCRIPTOR' : _DOORSENSOR,
  '__module__' : 'door_pb2'
  # @@protoc_insertion_point(class_scope:DoorSensor)
  })
_sym_db.RegisterMessage(DoorSensor)


# @@protoc_insertion_point(module_scope)
